### ISSUE TITLE
Encoding strings in the url Parameter

### ISSUE THREAD

**Issue by neilsilver** [dkershner6/post-api-call-action#1]
This might be a usage misunderstanding rather than an issue.

However the problem I have is I am trying to send a post request like this

apibase?title=TESTTITLE&content=TESTCONTENT   -  THIS WORKS

apibase?title=TEST TITLE&content=TEST CONTENT   - THIS DOESNT

apibase?title=TEST%20TITLE&content=TEST%20CONTENT  - THIS works 

I wonder if it would be possible to do a encodeURI() on the url parameter before passing it to the request

**Comment by dkershner6** [comment]
I am not sure there will be a way to both correctly parse that middle URL and encode it, simply because it isn't a valid URL to begin with (with a space in it)...

BUT, I think allowing for a query parameters object instead is likely to solve your use case (and allow spaces).

**Comment by neilsilver** [comment]
Yes a query Parameters Object would be great ! 

I have managed to workaround doing lots of Search and Replace in the Action but would be a good feature I think

**Comment by dkershner6** [comment]
You should be good to go here, @neilsilver , README is updated to reflect the new field using your example.
